### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.Update
  commentId: N:VDS.RDF.Web.Configuration.Update
  id: VDS.RDF.Web.Configuration.Update
  children:
  - VDS.RDF.Web.Configuration.Update.BaseUpdateHandlerConfiguration
  - VDS.RDF.Web.Configuration.Update.UpdateHandlerConfiguration
  langs:
  - csharp
  - vb
  name: VDS.RDF.Web.Configuration.Update
  nameWithType: VDS.RDF.Web.Configuration.Update
  fullName: VDS.RDF.Web.Configuration.Update
  type: Namespace
  assemblies:
  - dotNetRDF.Web
references:
- uid: VDS.RDF.Web.Configuration.Update.BaseUpdateHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Update.BaseUpdateHandlerConfiguration
  parent: VDS.RDF.Web.Configuration.Update
  name: BaseUpdateHandlerConfiguration
  nameWithType: BaseUpdateHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Update.BaseUpdateHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Update.UpdateHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Update.UpdateHandlerConfiguration
  name: UpdateHandlerConfiguration
  nameWithType: UpdateHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Update.UpdateHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Update
  commentId: N:VDS.RDF.Web.Configuration.Update
  name: VDS.RDF.Web.Configuration.Update
  nameWithType: VDS.RDF.Web.Configuration.Update
  fullName: VDS.RDF.Web.Configuration.Update
shouldSkipMarkup: true
