### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.Permissions
  commentId: N:VDS.RDF.Configuration.Permissions
  id: VDS.RDF.Configuration.Permissions
  children:
  - VDS.RDF.Configuration.Permissions.IPermission
  - VDS.RDF.Configuration.Permissions.Permission
  - VDS.RDF.Configuration.Permissions.PermissionModel
  - VDS.RDF.Configuration.Permissions.PermissionSet
  - VDS.RDF.Configuration.Permissions.UserGroup
  langs:
  - csharp
  - vb
  name: VDS.RDF.Configuration.Permissions
  nameWithType: VDS.RDF.Configuration.Permissions
  fullName: VDS.RDF.Configuration.Permissions
  type: Namespace
  assemblies:
  - dotNetRDF
references:
- uid: VDS.RDF.Configuration.Permissions.PermissionModel
  commentId: T:VDS.RDF.Configuration.Permissions.PermissionModel
  parent: VDS.RDF.Configuration.Permissions
  name: PermissionModel
  nameWithType: PermissionModel
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel
- uid: VDS.RDF.Configuration.Permissions.IPermission
  commentId: T:VDS.RDF.Configuration.Permissions.IPermission
  parent: VDS.RDF.Configuration.Permissions
  name: IPermission
  nameWithType: IPermission
  fullName: VDS.RDF.Configuration.Permissions.IPermission
- uid: VDS.RDF.Configuration.Permissions.Permission
  commentId: T:VDS.RDF.Configuration.Permissions.Permission
  name: Permission
  nameWithType: Permission
  fullName: VDS.RDF.Configuration.Permissions.Permission
- uid: VDS.RDF.Configuration.Permissions.PermissionSet
  commentId: T:VDS.RDF.Configuration.Permissions.PermissionSet
  name: PermissionSet
  nameWithType: PermissionSet
  fullName: VDS.RDF.Configuration.Permissions.PermissionSet
- uid: VDS.RDF.Configuration.Permissions.UserGroup
  commentId: T:VDS.RDF.Configuration.Permissions.UserGroup
  name: UserGroup
  nameWithType: UserGroup
  fullName: VDS.RDF.Configuration.Permissions.UserGroup
- uid: VDS.RDF.Configuration.Permissions
  commentId: N:VDS.RDF.Configuration.Permissions
  name: VDS.RDF.Configuration.Permissions
  nameWithType: VDS.RDF.Configuration.Permissions
  fullName: VDS.RDF.Configuration.Permissions
shouldSkipMarkup: true
