### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.IConfigurationLoader
  commentId: T:VDS.RDF.Configuration.IConfigurationLoader
  id: IConfigurationLoader
  parent: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.String)
  - VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.Uri)
  - VDS.RDF.Configuration.IConfigurationLoader.LoadObject``1(System.String)
  - VDS.RDF.Configuration.IConfigurationLoader.LoadObject``1(System.Uri)
  langs:
  - csharp
  - vb
  name: IConfigurationLoader
  nameWithType: IConfigurationLoader
  fullName: VDS.RDF.Configuration.IConfigurationLoader
  type: Interface
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: IConfigurationLoader
    path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
    startLine: 36
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nThe Configuration Loader is responsible for the loading of Configuration information \nand objects based upon information encoded in a Graph but more generally may be used \nfor the loading of any type of object whose configuration has been loaded in a Graph \nand for which a relevant <xref href=\"VDS.RDF.Configuration.IObjectFactory\" data-throw-if-not-resolved=\"false\"></xref> is available.\n"
  example: []
  syntax:
    content: public interface IConfigurationLoader
    content.vb: Public Interface IConfigurationLoader
  extensionMethods:
  - VDS.RDF.Configuration.IConfigurationLoader.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VDS.RDF.Configuration.IConfigurationLoader.LoadObject``1(System.Uri)
  commentId: M:VDS.RDF.Configuration.IConfigurationLoader.LoadObject``1(System.Uri)
  id: LoadObject``1(System.Uri)
  parent: VDS.RDF.Configuration.IConfigurationLoader
  langs:
  - csharp
  - vb
  name: LoadObject<T>(Uri)
  nameWithType: IConfigurationLoader.LoadObject<T>(Uri)
  fullName: VDS.RDF.Configuration.IConfigurationLoader.LoadObject<T>(System.Uri)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: LoadObject
    path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
    startLine: 44
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nLoads the Object identified by the given URI as an object of the given type based on information from the Configuration Graph.\n"
  remarks: "\nSee remarks under <xref href=\"VDS.RDF.Configuration.ConfigurationLoader.LoadObject(VDS.RDF.IGraph%2cVDS.RDF.INode)\" data-throw-if-not-resolved=\"false\"></xref>. \n"
  example: []
  syntax:
    content: T LoadObject<T>(Uri objectIdentifier)
    parameters:
    - id: objectIdentifier
      type: System.Uri
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Function LoadObject(Of T)(objectIdentifier As Uri) As T
  overload: VDS.RDF.Configuration.IConfigurationLoader.LoadObject*
  nameWithType.vb: IConfigurationLoader.LoadObject(Of T)(Uri)
  fullName.vb: VDS.RDF.Configuration.IConfigurationLoader.LoadObject(Of T)(System.Uri)
  name.vb: LoadObject(Of T)(Uri)
- uid: VDS.RDF.Configuration.IConfigurationLoader.LoadObject``1(System.String)
  commentId: M:VDS.RDF.Configuration.IConfigurationLoader.LoadObject``1(System.String)
  id: LoadObject``1(System.String)
  parent: VDS.RDF.Configuration.IConfigurationLoader
  langs:
  - csharp
  - vb
  name: LoadObject<T>(String)
  nameWithType: IConfigurationLoader.LoadObject<T>(String)
  fullName: VDS.RDF.Configuration.IConfigurationLoader.LoadObject<T>(System.String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: LoadObject
    path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
    startLine: 52
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nLoads the Object identified by the given blank node identifier as an object of the given type based on information from the Configuration Graph.\n"
  remarks: "\nSee remarks under <xref href=\"VDS.RDF.Configuration.ConfigurationLoader.LoadObject(VDS.RDF.IGraph%2cVDS.RDF.INode)\" data-throw-if-not-resolved=\"false\"></xref>. \n"
  example: []
  syntax:
    content: T LoadObject<T>(string blankNodeIdentifier)
    parameters:
    - id: blankNodeIdentifier
      type: System.String
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Function LoadObject(Of T)(blankNodeIdentifier As String) As T
  overload: VDS.RDF.Configuration.IConfigurationLoader.LoadObject*
  nameWithType.vb: IConfigurationLoader.LoadObject(Of T)(String)
  fullName.vb: VDS.RDF.Configuration.IConfigurationLoader.LoadObject(Of T)(System.String)
  name.vb: LoadObject(Of T)(String)
- uid: VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.String)
  commentId: M:VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.String)
  id: LoadObject(System.String)
  parent: VDS.RDF.Configuration.IConfigurationLoader
  langs:
  - csharp
  - vb
  name: LoadObject(String)
  nameWithType: IConfigurationLoader.LoadObject(String)
  fullName: VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: LoadObject
    path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
    startLine: 60
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nLoads the Object identified by the given blank node identifier as an <xref href=\"System.Object\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  remarks: "\nSee remarks under <xref href=\"VDS.RDF.Configuration.ConfigurationLoader.LoadObject(VDS.RDF.IGraph%2cVDS.RDF.INode)\" data-throw-if-not-resolved=\"false\"></xref>. \n"
  example: []
  syntax:
    content: object LoadObject(string blankNodeIdentifier)
    parameters:
    - id: blankNodeIdentifier
      type: System.String
    return:
      type: System.Object
    content.vb: Function LoadObject(blankNodeIdentifier As String) As Object
  overload: VDS.RDF.Configuration.IConfigurationLoader.LoadObject*
- uid: VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.Uri)
  commentId: M:VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.Uri)
  id: LoadObject(System.Uri)
  parent: VDS.RDF.Configuration.IConfigurationLoader
  langs:
  - csharp
  - vb
  name: LoadObject(Uri)
  nameWithType: IConfigurationLoader.LoadObject(Uri)
  fullName: VDS.RDF.Configuration.IConfigurationLoader.LoadObject(System.Uri)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: LoadObject
    path: Libraries/dotNetRDF/Configuration/IConfigurationLoader.cs
    startLine: 68
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nLoads the Object identified by the given URI as an <xref href=\"System.Object\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  remarks: "\nSee remarks under <xref href=\"VDS.RDF.Configuration.ConfigurationLoader.LoadObject(VDS.RDF.IGraph%2cVDS.RDF.INode)\" data-throw-if-not-resolved=\"false\"></xref>. \n"
  example: []
  syntax:
    content: object LoadObject(Uri objectIdentifier)
    parameters:
    - id: objectIdentifier
      type: System.Uri
    return:
      type: System.Object
    content.vb: Function LoadObject(objectIdentifier As Uri) As Object
  overload: VDS.RDF.Configuration.IConfigurationLoader.LoadObject*
references:
- uid: VDS.RDF.Configuration.IObjectFactory
  commentId: T:VDS.RDF.Configuration.IObjectFactory
  parent: VDS.RDF.Configuration
  name: IObjectFactory
  nameWithType: IObjectFactory
  fullName: VDS.RDF.Configuration.IObjectFactory
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: VDS.RDF.Configuration.IConfigurationLoader.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<IConfigurationLoader>()
  nameWithType: Extensions.AsEnumerable<IConfigurationLoader>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IConfigurationLoader>()
  nameWithType.vb: Extensions.AsEnumerable(Of IConfigurationLoader)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IConfigurationLoader)()
  name.vb: AsEnumerable(Of IConfigurationLoader)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<IConfigurationLoader>
    nameWithType: Extensions.AsEnumerable<IConfigurationLoader>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IConfigurationLoader>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of IConfigurationLoader)
    nameWithType: Extensions.AsEnumerable(Of IConfigurationLoader)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IConfigurationLoader)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.ConfigurationLoader.LoadObject(VDS.RDF.IGraph,VDS.RDF.INode)
  commentId: M:VDS.RDF.Configuration.ConfigurationLoader.LoadObject(VDS.RDF.IGraph,VDS.RDF.INode)
  isExternal: true
- uid: VDS.RDF.Configuration.IConfigurationLoader.LoadObject*
  commentId: Overload:VDS.RDF.Configuration.IConfigurationLoader.LoadObject
  name: LoadObject
  nameWithType: IConfigurationLoader.LoadObject
  fullName: VDS.RDF.Configuration.IConfigurationLoader.LoadObject
- uid: System.Uri
  commentId: T:System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
shouldSkipMarkup: true
