### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.Server
  commentId: N:VDS.RDF.Web.Configuration.Server
  id: VDS.RDF.Web.Configuration.Server
  children:
  - VDS.RDF.Web.Configuration.Server.BaseSparqlServerConfiguration
  - VDS.RDF.Web.Configuration.Server.SparqlServerConfiguration
  langs:
  - csharp
  - vb
  name: VDS.RDF.Web.Configuration.Server
  nameWithType: VDS.RDF.Web.Configuration.Server
  fullName: VDS.RDF.Web.Configuration.Server
  type: Namespace
  assemblies:
  - dotNetRDF.Web
references:
- uid: VDS.RDF.Web.Configuration.Server.BaseSparqlServerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Server.BaseSparqlServerConfiguration
  parent: VDS.RDF.Web.Configuration.Server
  name: BaseSparqlServerConfiguration
  nameWithType: BaseSparqlServerConfiguration
  fullName: VDS.RDF.Web.Configuration.Server.BaseSparqlServerConfiguration
- uid: VDS.RDF.Web.Configuration.Server.SparqlServerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Server.SparqlServerConfiguration
  name: SparqlServerConfiguration
  nameWithType: SparqlServerConfiguration
  fullName: VDS.RDF.Web.Configuration.Server.SparqlServerConfiguration
- uid: VDS.RDF.Web.Configuration.Server
  commentId: N:VDS.RDF.Web.Configuration.Server
  name: VDS.RDF.Web.Configuration.Server
  nameWithType: VDS.RDF.Web.Configuration.Server
  fullName: VDS.RDF.Web.Configuration.Server
shouldSkipMarkup: true
