### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  id: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.CollectionFactory
  - VDS.RDF.Configuration.ConfigurationLoader
  - VDS.RDF.Configuration.ConfigurationManagerSettingsProvider
  - VDS.RDF.Configuration.ConfigurationSerializationContext
  - VDS.RDF.Configuration.CredentialsFactory
  - VDS.RDF.Configuration.DatasetFactory
  - VDS.RDF.Configuration.DotNetRdfConfigurationException
  - VDS.RDF.Configuration.ExpressionFactoryFactory
  - VDS.RDF.Configuration.FullTextObjectFactory
  - VDS.RDF.Configuration.GraphFactory
  - VDS.RDF.Configuration.IConfigurationLoader
  - VDS.RDF.Configuration.IConfigurationSerializable
  - VDS.RDF.Configuration.IObjectFactory
  - VDS.RDF.Configuration.IPathResolver
  - VDS.RDF.Configuration.ISettingsProvider
  - VDS.RDF.Configuration.ObjectFactoryFactory
  - VDS.RDF.Configuration.OperatorFactory
  - VDS.RDF.Configuration.OptimiserFactory
  - VDS.RDF.Configuration.ParserFactory
  - VDS.RDF.Configuration.PermissionFactory
  - VDS.RDF.Configuration.PropertyFunctionFactoryFactory
  - VDS.RDF.Configuration.ProtocolProcessorFactory
  - VDS.RDF.Configuration.ProxyFactory
  - VDS.RDF.Configuration.QueryProcessorFactory
  - VDS.RDF.Configuration.ReasonerFactory
  - VDS.RDF.Configuration.SparqlEndpointFactory
  - VDS.RDF.Configuration.StorageFactory
  - VDS.RDF.Configuration.StoreFactory
  - VDS.RDF.Configuration.UpdateProcessorFactory
  - VDS.RDF.Configuration.UserGroupFactory
  - VDS.RDF.Configuration.VirtuosoObjectFactory
  - VDS.RDF.Configuration.WriterFactory
  langs:
  - csharp
  - vb
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
  type: Namespace
  assemblies:
  - dotNetRDF
references:
- uid: VDS.RDF.Configuration.CollectionFactory
  commentId: T:VDS.RDF.Configuration.CollectionFactory
  name: CollectionFactory
  nameWithType: CollectionFactory
  fullName: VDS.RDF.Configuration.CollectionFactory
- uid: VDS.RDF.Configuration.IObjectFactory
  commentId: T:VDS.RDF.Configuration.IObjectFactory
  parent: VDS.RDF.Configuration
  name: IObjectFactory
  nameWithType: IObjectFactory
  fullName: VDS.RDF.Configuration.IObjectFactory
- uid: VDS.RDF.Configuration.IConfigurationSerializable
  commentId: T:VDS.RDF.Configuration.IConfigurationSerializable
  parent: VDS.RDF.Configuration
  name: IConfigurationSerializable
  nameWithType: IConfigurationSerializable
  fullName: VDS.RDF.Configuration.IConfigurationSerializable
- uid: VDS.RDF.Configuration.IPathResolver
  commentId: T:VDS.RDF.Configuration.IPathResolver
  parent: VDS.RDF.Configuration
  name: IPathResolver
  nameWithType: IPathResolver
  fullName: VDS.RDF.Configuration.IPathResolver
- uid: VDS.RDF.Configuration.ConfigurationLoader
  commentId: T:VDS.RDF.Configuration.ConfigurationLoader
  name: ConfigurationLoader
  nameWithType: ConfigurationLoader
  fullName: VDS.RDF.Configuration.ConfigurationLoader
- uid: VDS.RDF.Configuration.ConfigurationManagerSettingsProvider
  commentId: T:VDS.RDF.Configuration.ConfigurationManagerSettingsProvider
  name: ConfigurationManagerSettingsProvider
  nameWithType: ConfigurationManagerSettingsProvider
  fullName: VDS.RDF.Configuration.ConfigurationManagerSettingsProvider
- uid: VDS.RDF.Configuration.ConfigurationSerializationContext
  commentId: T:VDS.RDF.Configuration.ConfigurationSerializationContext
  parent: VDS.RDF.Configuration
  name: ConfigurationSerializationContext
  nameWithType: ConfigurationSerializationContext
  fullName: VDS.RDF.Configuration.ConfigurationSerializationContext
- uid: VDS.RDF.Configuration.CredentialsFactory
  commentId: T:VDS.RDF.Configuration.CredentialsFactory
  name: CredentialsFactory
  nameWithType: CredentialsFactory
  fullName: VDS.RDF.Configuration.CredentialsFactory
- uid: VDS.RDF.Configuration.GraphFactory
  commentId: T:VDS.RDF.Configuration.GraphFactory
  name: GraphFactory
  nameWithType: GraphFactory
  fullName: VDS.RDF.Configuration.GraphFactory
- uid: VDS.RDF.Configuration.StoreFactory
  commentId: T:VDS.RDF.Configuration.StoreFactory
  name: StoreFactory
  nameWithType: StoreFactory
  fullName: VDS.RDF.Configuration.StoreFactory
- uid: VDS.RDF.Configuration.DatasetFactory
  commentId: T:VDS.RDF.Configuration.DatasetFactory
  name: DatasetFactory
  nameWithType: DatasetFactory
  fullName: VDS.RDF.Configuration.DatasetFactory
- uid: VDS.RDF.Configuration.SparqlEndpointFactory
  commentId: T:VDS.RDF.Configuration.SparqlEndpointFactory
  name: SparqlEndpointFactory
  nameWithType: SparqlEndpointFactory
  fullName: VDS.RDF.Configuration.SparqlEndpointFactory
- uid: VDS.RDF.Configuration.ExpressionFactoryFactory
  commentId: T:VDS.RDF.Configuration.ExpressionFactoryFactory
  name: ExpressionFactoryFactory
  nameWithType: ExpressionFactoryFactory
  fullName: VDS.RDF.Configuration.ExpressionFactoryFactory
- uid: VDS.RDF.Configuration.IConfigurationLoader
  commentId: T:VDS.RDF.Configuration.IConfigurationLoader
  parent: VDS.RDF.Configuration
  name: IConfigurationLoader
  nameWithType: IConfigurationLoader
  fullName: VDS.RDF.Configuration.IConfigurationLoader
- uid: VDS.RDF.Configuration.ISettingsProvider
  commentId: T:VDS.RDF.Configuration.ISettingsProvider
  parent: VDS.RDF.Configuration
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: VDS.RDF.Configuration.ISettingsProvider
- uid: VDS.RDF.Configuration.ObjectFactoryFactory
  commentId: T:VDS.RDF.Configuration.ObjectFactoryFactory
  name: ObjectFactoryFactory
  nameWithType: ObjectFactoryFactory
  fullName: VDS.RDF.Configuration.ObjectFactoryFactory
- uid: VDS.RDF.Configuration.OperatorFactory
  commentId: T:VDS.RDF.Configuration.OperatorFactory
  name: OperatorFactory
  nameWithType: OperatorFactory
  fullName: VDS.RDF.Configuration.OperatorFactory
- uid: VDS.RDF.Configuration.OptimiserFactory
  commentId: T:VDS.RDF.Configuration.OptimiserFactory
  name: OptimiserFactory
  nameWithType: OptimiserFactory
  fullName: VDS.RDF.Configuration.OptimiserFactory
- uid: VDS.RDF.Configuration.ParserFactory
  commentId: T:VDS.RDF.Configuration.ParserFactory
  name: ParserFactory
  nameWithType: ParserFactory
  fullName: VDS.RDF.Configuration.ParserFactory
- uid: VDS.RDF.Configuration.WriterFactory
  commentId: T:VDS.RDF.Configuration.WriterFactory
  name: WriterFactory
  nameWithType: WriterFactory
  fullName: VDS.RDF.Configuration.WriterFactory
- uid: VDS.RDF.Configuration.PermissionFactory
  commentId: T:VDS.RDF.Configuration.PermissionFactory
  name: PermissionFactory
  nameWithType: PermissionFactory
  fullName: VDS.RDF.Configuration.PermissionFactory
- uid: VDS.RDF.Configuration.UserGroupFactory
  commentId: T:VDS.RDF.Configuration.UserGroupFactory
  name: UserGroupFactory
  nameWithType: UserGroupFactory
  fullName: VDS.RDF.Configuration.UserGroupFactory
- uid: VDS.RDF.Configuration.QueryProcessorFactory
  commentId: T:VDS.RDF.Configuration.QueryProcessorFactory
  name: QueryProcessorFactory
  nameWithType: QueryProcessorFactory
  fullName: VDS.RDF.Configuration.QueryProcessorFactory
- uid: VDS.RDF.Configuration.UpdateProcessorFactory
  commentId: T:VDS.RDF.Configuration.UpdateProcessorFactory
  name: UpdateProcessorFactory
  nameWithType: UpdateProcessorFactory
  fullName: VDS.RDF.Configuration.UpdateProcessorFactory
- uid: VDS.RDF.Configuration.ProtocolProcessorFactory
  commentId: T:VDS.RDF.Configuration.ProtocolProcessorFactory
  name: ProtocolProcessorFactory
  nameWithType: ProtocolProcessorFactory
  fullName: VDS.RDF.Configuration.ProtocolProcessorFactory
- uid: VDS.RDF.Configuration.PropertyFunctionFactoryFactory
  commentId: T:VDS.RDF.Configuration.PropertyFunctionFactoryFactory
  name: PropertyFunctionFactoryFactory
  nameWithType: PropertyFunctionFactoryFactory
  fullName: VDS.RDF.Configuration.PropertyFunctionFactoryFactory
- uid: VDS.RDF.Configuration.ProxyFactory
  commentId: T:VDS.RDF.Configuration.ProxyFactory
  name: ProxyFactory
  nameWithType: ProxyFactory
  fullName: VDS.RDF.Configuration.ProxyFactory
- uid: VDS.RDF.Configuration.ReasonerFactory
  commentId: T:VDS.RDF.Configuration.ReasonerFactory
  name: ReasonerFactory
  nameWithType: ReasonerFactory
  fullName: VDS.RDF.Configuration.ReasonerFactory
- uid: VDS.RDF.Configuration.StorageFactory
  commentId: T:VDS.RDF.Configuration.StorageFactory
  name: StorageFactory
  nameWithType: StorageFactory
  fullName: VDS.RDF.Configuration.StorageFactory
- uid: VDS.RDF.Configuration.DotNetRdfConfigurationException
  commentId: T:VDS.RDF.Configuration.DotNetRdfConfigurationException
  name: DotNetRdfConfigurationException
  nameWithType: DotNetRdfConfigurationException
  fullName: VDS.RDF.Configuration.DotNetRdfConfigurationException
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory
  commentId: T:VDS.RDF.Configuration.VirtuosoObjectFactory
  name: VirtuosoObjectFactory
  nameWithType: VirtuosoObjectFactory
  fullName: VDS.RDF.Configuration.VirtuosoObjectFactory
- uid: VDS.RDF.Configuration.FullTextObjectFactory
  commentId: T:VDS.RDF.Configuration.FullTextObjectFactory
  name: FullTextObjectFactory
  nameWithType: FullTextObjectFactory
  fullName: VDS.RDF.Configuration.FullTextObjectFactory
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
shouldSkipMarkup: true
