### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory
  commentId: T:VDS.RDF.Configuration.VirtuosoObjectFactory
  id: VirtuosoObjectFactory
  parent: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject(Type)
  - VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,Type,System.Object@)
  langs:
  - csharp
  - vb
  name: VirtuosoObjectFactory
  nameWithType: VirtuosoObjectFactory
  fullName: VDS.RDF.Configuration.VirtuosoObjectFactory
  type: Class
  source:
    remote:
      path: Libraries/dotNetRDF.Data.Virtuoso/VirtuosoObjectFactory.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: VirtuosoObjectFactory
    path: Libraries/dotNetRDF.Data.Virtuoso/VirtuosoObjectFactory.cs
    startLine: 34
  assemblies:
  - dotNetRDF.Data.Virtuoso
  namespace: VDS.RDF.Configuration
  summary: "\nAn Object Factory that can create objects of the classes provided by the dotNetRDF.Data.Virtuoso library.\n"
  example: []
  syntax:
    content: 'public class VirtuosoObjectFactory : object, IObjectFactory'
    content.vb: >-
      Public Class VirtuosoObjectFactory
          Inherits Object
          Implements IObjectFactory
  inheritance:
  - System.Object
  implements:
  - VDS.RDF.Configuration.IObjectFactory
  extensionMethods:
  - VDS.RDF.Configuration.VirtuosoObjectFactory.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,Type,System.Object@)
  commentId: M:VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,Type,System.Object@)
  id: TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,Type,System.Object@)
  parent: VDS.RDF.Configuration.VirtuosoObjectFactory
  langs:
  - csharp
  - vb
  name: TryLoadObject(IGraph, INode, Type, out Object)
  nameWithType: VirtuosoObjectFactory.TryLoadObject(IGraph, INode, Type, out Object)
  fullName: VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject(VDS.RDF.IGraph, VDS.RDF.INode, Type, out System.Object)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF.Data.Virtuoso/VirtuosoObjectFactory.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: TryLoadObject
    path: Libraries/dotNetRDF.Data.Virtuoso/VirtuosoObjectFactory.cs
    startLine: 47
  assemblies:
  - dotNetRDF.Data.Virtuoso
  namespace: VDS.RDF.Configuration
  summary: "\nAttempts to load an Object of the given type identified by the given Node and returned as the Type that this loader generates.\n"
  example: []
  syntax:
    content: public bool TryLoadObject(IGraph g, INode objNode, Type targetType, out object obj)
    parameters:
    - id: g
      type: VDS.RDF.IGraph
      description: Configuration Graph.
    - id: objNode
      type: VDS.RDF.INode
      description: Object Node.
    - id: targetType
      type: Type
      description: Target Type.
    - id: obj
      type: System.Object
      description: Created Object.
    return:
      type: System.Boolean
      description: True if the loader succeeded in creating an Object.
    content.vb: Public Function TryLoadObject(g As IGraph, objNode As INode, targetType As Type, ByRef obj As Object) As Boolean
  overload: VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject*
  nameWithType.vb: VirtuosoObjectFactory.TryLoadObject(IGraph, INode, Type, ByRef Object)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject(VDS.RDF.IGraph, VDS.RDF.INode, Type, ByRef System.Object)
  name.vb: TryLoadObject(IGraph, INode, Type, ByRef Object)
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject(Type)
  commentId: M:VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject(Type)
  id: CanLoadObject(Type)
  parent: VDS.RDF.Configuration.VirtuosoObjectFactory
  langs:
  - csharp
  - vb
  name: CanLoadObject(Type)
  nameWithType: VirtuosoObjectFactory.CanLoadObject(Type)
  fullName: VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject(Type)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF.Data.Virtuoso/VirtuosoObjectFactory.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: CanLoadObject
    path: Libraries/dotNetRDF.Data.Virtuoso/VirtuosoObjectFactory.cs
    startLine: 96
  assemblies:
  - dotNetRDF.Data.Virtuoso
  namespace: VDS.RDF.Configuration
  summary: "\nReturns whether this Factory is capable of creating objects of the given type.\n"
  example: []
  syntax:
    content: public bool CanLoadObject(Type t)
    parameters:
    - id: t
      type: Type
      description: Target Type.
    return:
      type: System.Boolean
      description: ''
    content.vb: Public Function CanLoadObject(t As Type) As Boolean
  overload: VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VDS.RDF.Configuration.IObjectFactory
  commentId: T:VDS.RDF.Configuration.IObjectFactory
  parent: VDS.RDF.Configuration
  name: IObjectFactory
  nameWithType: IObjectFactory
  fullName: VDS.RDF.Configuration.IObjectFactory
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<VirtuosoObjectFactory>()
  nameWithType: Extensions.AsEnumerable<VirtuosoObjectFactory>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.VirtuosoObjectFactory>()
  nameWithType.vb: Extensions.AsEnumerable(Of VirtuosoObjectFactory)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.VirtuosoObjectFactory)()
  name.vb: AsEnumerable(Of VirtuosoObjectFactory)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<VirtuosoObjectFactory>
    nameWithType: Extensions.AsEnumerable<VirtuosoObjectFactory>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.VirtuosoObjectFactory>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of VirtuosoObjectFactory)
    nameWithType: Extensions.AsEnumerable(Of VirtuosoObjectFactory)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.VirtuosoObjectFactory)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject*
  commentId: Overload:VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject
  name: TryLoadObject
  nameWithType: VirtuosoObjectFactory.TryLoadObject
  fullName: VDS.RDF.Configuration.VirtuosoObjectFactory.TryLoadObject
- uid: VDS.RDF.IGraph
  commentId: T:VDS.RDF.IGraph
  parent: VDS.RDF
  name: IGraph
  nameWithType: IGraph
  fullName: VDS.RDF.IGraph
- uid: VDS.RDF.INode
  commentId: T:VDS.RDF.INode
  parent: VDS.RDF
  name: INode
  nameWithType: INode
  fullName: VDS.RDF.INode
- uid: Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: Type
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject*
  commentId: Overload:VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject
  name: CanLoadObject
  nameWithType: VirtuosoObjectFactory.CanLoadObject
  fullName: VDS.RDF.Configuration.VirtuosoObjectFactory.CanLoadObject
shouldSkipMarkup: true
