### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration
  commentId: N:VDS.RDF.Web.Configuration
  id: VDS.RDF.Web.Configuration
  children:
  - VDS.RDF.Web.Configuration.BaseHandlerConfiguration
  - VDS.RDF.Web.Configuration.WebConfigurationLoader
  - VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  langs:
  - csharp
  - vb
  name: VDS.RDF.Web.Configuration
  nameWithType: VDS.RDF.Web.Configuration
  fullName: VDS.RDF.Web.Configuration
  type: Namespace
  assemblies:
  - dotNetRDF.Web
references:
- uid: VDS.RDF.Web.Configuration.BaseHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.BaseHandlerConfiguration
  parent: VDS.RDF.Web.Configuration
  name: BaseHandlerConfiguration
  nameWithType: BaseHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.BaseHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader
  commentId: T:VDS.RDF.Web.Configuration.WebConfigurationLoader
  name: WebConfigurationLoader
  nameWithType: WebConfigurationLoader
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  commentId: T:VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  name: WebConfigurationPathResolver
  nameWithType: WebConfigurationPathResolver
  fullName: VDS.RDF.Web.Configuration.WebConfigurationPathResolver
- uid: VDS.RDF.Web.Configuration
  commentId: N:VDS.RDF.Web.Configuration
  name: VDS.RDF.Web.Configuration
  nameWithType: VDS.RDF.Web.Configuration
  fullName: VDS.RDF.Web.Configuration
shouldSkipMarkup: true
