### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.Permissions.PermissionModel
  commentId: T:VDS.RDF.Configuration.Permissions.PermissionModel
  id: PermissionModel
  parent: VDS.RDF.Configuration.Permissions
  children:
  - VDS.RDF.Configuration.Permissions.PermissionModel.AllowAny
  - VDS.RDF.Configuration.Permissions.PermissionModel.AllowDeny
  - VDS.RDF.Configuration.Permissions.PermissionModel.DenyAllow
  - VDS.RDF.Configuration.Permissions.PermissionModel.DenyAny
  langs:
  - csharp
  - vb
  name: PermissionModel
  nameWithType: PermissionModel
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel
  type: Enum
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: PermissionModel
    path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 35
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nPossible permission models.\n"
  example: []
  syntax:
    content: public enum PermissionModel
    content.vb: Public Enum PermissionModel
  extensionMethods:
  - VDS.RDF.Configuration.Permissions.PermissionModel.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: VDS.RDF.Configuration.Permissions.PermissionModel.DenyAllow
  commentId: F:VDS.RDF.Configuration.Permissions.PermissionModel.DenyAllow
  id: DenyAllow
  parent: VDS.RDF.Configuration.Permissions.PermissionModel
  langs:
  - csharp
  - vb
  name: DenyAllow
  nameWithType: PermissionModel.DenyAllow
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel.DenyAllow
  type: Field
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: DenyAllow
    path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 40
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nIf the action appears in the deny list it is denied unless it is in the allow list, otherwise it is allowed\n"
  example: []
  syntax:
    content: DenyAllow = 0
    return:
      type: VDS.RDF.Configuration.Permissions.PermissionModel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VDS.RDF.Configuration.Permissions.PermissionModel.AllowDeny
  commentId: F:VDS.RDF.Configuration.Permissions.PermissionModel.AllowDeny
  id: AllowDeny
  parent: VDS.RDF.Configuration.Permissions.PermissionModel
  langs:
  - csharp
  - vb
  name: AllowDeny
  nameWithType: PermissionModel.AllowDeny
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel.AllowDeny
  type: Field
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: AllowDeny
    path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 44
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nIf the action appears in the allow list it is allowed unless it is in the deny list, otherwise it is denied\n"
  example: []
  syntax:
    content: AllowDeny = 1
    return:
      type: VDS.RDF.Configuration.Permissions.PermissionModel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VDS.RDF.Configuration.Permissions.PermissionModel.AllowAny
  commentId: F:VDS.RDF.Configuration.Permissions.PermissionModel.AllowAny
  id: AllowAny
  parent: VDS.RDF.Configuration.Permissions.PermissionModel
  langs:
  - csharp
  - vb
  name: AllowAny
  nameWithType: PermissionModel.AllowAny
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel.AllowAny
  type: Field
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: AllowAny
    path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 48
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nAll actions are allowed\n"
  example: []
  syntax:
    content: AllowAny = 2
    return:
      type: VDS.RDF.Configuration.Permissions.PermissionModel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VDS.RDF.Configuration.Permissions.PermissionModel.DenyAny
  commentId: F:VDS.RDF.Configuration.Permissions.PermissionModel.DenyAny
  id: DenyAny
  parent: VDS.RDF.Configuration.Permissions.PermissionModel
  langs:
  - csharp
  - vb
  name: DenyAny
  nameWithType: PermissionModel.DenyAny
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel.DenyAny
  type: Field
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: DenyAny
    path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 52
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nAll actions are denied\n"
  example: []
  syntax:
    content: DenyAny = 3
    return:
      type: VDS.RDF.Configuration.Permissions.PermissionModel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: VDS.RDF.Configuration.Permissions
  commentId: N:VDS.RDF.Configuration.Permissions
  name: VDS.RDF.Configuration.Permissions
  nameWithType: VDS.RDF.Configuration.Permissions
  fullName: VDS.RDF.Configuration.Permissions
- uid: VDS.RDF.Configuration.Permissions.PermissionModel.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<PermissionModel>()
  nameWithType: Extensions.AsEnumerable<PermissionModel>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.Permissions.PermissionModel>()
  nameWithType.vb: Extensions.AsEnumerable(Of PermissionModel)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.Permissions.PermissionModel)()
  name.vb: AsEnumerable(Of PermissionModel)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<PermissionModel>
    nameWithType: Extensions.AsEnumerable<PermissionModel>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.Permissions.PermissionModel>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of PermissionModel)
    nameWithType: Extensions.AsEnumerable(Of PermissionModel)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.Permissions.PermissionModel)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.Permissions.PermissionModel
  commentId: T:VDS.RDF.Configuration.Permissions.PermissionModel
  parent: VDS.RDF.Configuration.Permissions
  name: PermissionModel
  nameWithType: PermissionModel
  fullName: VDS.RDF.Configuration.Permissions.PermissionModel
shouldSkipMarkup: true
