### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.IConfigurationSerializable
  commentId: T:VDS.RDF.Configuration.IConfigurationSerializable
  id: IConfigurationSerializable
  parent: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration(VDS.RDF.Configuration.ConfigurationSerializationContext)
  langs:
  - csharp
  - vb
  name: IConfigurationSerializable
  nameWithType: IConfigurationSerializable
  fullName: VDS.RDF.Configuration.IConfigurationSerializable
  type: Interface
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: IConfigurationSerializable
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 61
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nInterface for Objects which can have their configuration serialized to RDF.\n"
  example: []
  syntax:
    content: public interface IConfigurationSerializable
    content.vb: Public Interface IConfigurationSerializable
  extensionMethods:
  - VDS.RDF.Configuration.IConfigurationSerializable.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration(VDS.RDF.Configuration.ConfigurationSerializationContext)
  commentId: M:VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration(VDS.RDF.Configuration.ConfigurationSerializationContext)
  id: SerializeConfiguration(VDS.RDF.Configuration.ConfigurationSerializationContext)
  parent: VDS.RDF.Configuration.IConfigurationSerializable
  langs:
  - csharp
  - vb
  name: SerializeConfiguration(ConfigurationSerializationContext)
  nameWithType: IConfigurationSerializable.SerializeConfiguration(ConfigurationSerializationContext)
  fullName: VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration(VDS.RDF.Configuration.ConfigurationSerializationContext)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: SerializeConfiguration
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 67
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nSerializes the Configuration in the given context.\n"
  example: []
  syntax:
    content: void SerializeConfiguration(ConfigurationSerializationContext context)
    parameters:
    - id: context
      type: VDS.RDF.Configuration.ConfigurationSerializationContext
      description: Configuration Serialization Context.
    content.vb: Sub SerializeConfiguration(context As ConfigurationSerializationContext)
  overload: VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration*
references:
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: VDS.RDF.Configuration.IConfigurationSerializable.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<IConfigurationSerializable>()
  nameWithType: Extensions.AsEnumerable<IConfigurationSerializable>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IConfigurationSerializable>()
  nameWithType.vb: Extensions.AsEnumerable(Of IConfigurationSerializable)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IConfigurationSerializable)()
  name.vb: AsEnumerable(Of IConfigurationSerializable)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<IConfigurationSerializable>
    nameWithType: Extensions.AsEnumerable<IConfigurationSerializable>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IConfigurationSerializable>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of IConfigurationSerializable)
    nameWithType: Extensions.AsEnumerable(Of IConfigurationSerializable)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IConfigurationSerializable)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration*
  commentId: Overload:VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration
  name: SerializeConfiguration
  nameWithType: IConfigurationSerializable.SerializeConfiguration
  fullName: VDS.RDF.Configuration.IConfigurationSerializable.SerializeConfiguration
- uid: VDS.RDF.Configuration.ConfigurationSerializationContext
  commentId: T:VDS.RDF.Configuration.ConfigurationSerializationContext
  parent: VDS.RDF.Configuration
  name: ConfigurationSerializationContext
  nameWithType: ConfigurationSerializationContext
  fullName: VDS.RDF.Configuration.ConfigurationSerializationContext
