### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  commentId: T:VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  id: WebConfigurationPathResolver
  parent: VDS.RDF.Web.Configuration
  children:
  - VDS.RDF.Web.Configuration.WebConfigurationPathResolver.#ctor(HttpServerUtility)
  - VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath(System.String)
  langs:
  - csharp
  - vb
  name: WebConfigurationPathResolver
  nameWithType: WebConfigurationPathResolver
  fullName: VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  type: Class
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: WebConfigurationPathResolver
    path: ../../dotNetRDF/Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 116
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nPath Resolver for Web Configuration loading\n"
  example: []
  syntax:
    content: 'public class WebConfigurationPathResolver : object, IPathResolver'
    content.vb: >-
      Public Class WebConfigurationPathResolver
          Inherits Object
          Implements IPathResolver
  inheritance:
  - System.Object
  implements:
  - VDS.RDF.Configuration.IPathResolver
  extensionMethods:
  - VDS.RDF.Web.Configuration.WebConfigurationPathResolver.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.#ctor(HttpServerUtility)
  commentId: M:VDS.RDF.Web.Configuration.WebConfigurationPathResolver.#ctor(HttpServerUtility)
  id: '#ctor(HttpServerUtility)'
  parent: VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  langs:
  - csharp
  - vb
  name: WebConfigurationPathResolver(HttpServerUtility)
  nameWithType: WebConfigurationPathResolver.WebConfigurationPathResolver(HttpServerUtility)
  fullName: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.WebConfigurationPathResolver(HttpServerUtility)
  type: Constructor
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: .ctor
    path: ../../dotNetRDF/Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 125
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nCreates a new Web Configuration Path Resolver\n"
  example: []
  syntax:
    content: public WebConfigurationPathResolver(HttpServerUtility server)
    parameters:
    - id: server
      type: HttpServerUtility
      description: HTTP Server Utility
    content.vb: Public Sub New(server As HttpServerUtility)
  overload: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath(System.String)
  commentId: M:VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath(System.String)
  id: ResolvePath(System.String)
  parent: VDS.RDF.Web.Configuration.WebConfigurationPathResolver
  langs:
  - csharp
  - vb
  name: ResolvePath(String)
  nameWithType: WebConfigurationPathResolver.ResolvePath(String)
  fullName: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath(System.String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: ResolvePath
    path: ../../dotNetRDF/Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 135
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nResolves a Path by calling MapPath() where appropriate\n"
  example: []
  syntax:
    content: public string ResolvePath(string path)
    parameters:
    - id: path
      type: System.String
      description: Path
    return:
      type: System.String
      description: ''
    content.vb: Public Function ResolvePath(path As String) As String
  overload: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath*
  implements:
  - VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VDS.RDF.Web.Configuration
  commentId: N:VDS.RDF.Web.Configuration
  name: VDS.RDF.Web.Configuration
  nameWithType: VDS.RDF.Web.Configuration
  fullName: VDS.RDF.Web.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VDS.RDF.Configuration.IPathResolver
  commentId: T:VDS.RDF.Configuration.IPathResolver
  parent: VDS.RDF.Configuration
  name: IPathResolver
  nameWithType: IPathResolver
  fullName: VDS.RDF.Configuration.IPathResolver
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<WebConfigurationPathResolver>()
  nameWithType: Extensions.AsEnumerable<WebConfigurationPathResolver>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Web.Configuration.WebConfigurationPathResolver>()
  nameWithType.vb: Extensions.AsEnumerable(Of WebConfigurationPathResolver)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Web.Configuration.WebConfigurationPathResolver)()
  name.vb: AsEnumerable(Of WebConfigurationPathResolver)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<WebConfigurationPathResolver>
    nameWithType: Extensions.AsEnumerable<WebConfigurationPathResolver>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Web.Configuration.WebConfigurationPathResolver>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of WebConfigurationPathResolver)
    nameWithType: Extensions.AsEnumerable(Of WebConfigurationPathResolver)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Web.Configuration.WebConfigurationPathResolver)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.#ctor*
  commentId: Overload:VDS.RDF.Web.Configuration.WebConfigurationPathResolver.#ctor
  name: WebConfigurationPathResolver
  nameWithType: WebConfigurationPathResolver.WebConfigurationPathResolver
  fullName: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.WebConfigurationPathResolver
- uid: HttpServerUtility
  commentId: '!:HttpServerUtility'
  isExternal: true
  name: HttpServerUtility
  nameWithType: HttpServerUtility
  fullName: HttpServerUtility
- uid: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath*
  commentId: Overload:VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath
  name: ResolvePath
  nameWithType: WebConfigurationPathResolver.ResolvePath
  fullName: VDS.RDF.Web.Configuration.WebConfigurationPathResolver.ResolvePath
- uid: VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  commentId: M:VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  parent: VDS.RDF.Configuration.IPathResolver
  isExternal: true
  name: ResolvePath(String)
  nameWithType: IPathResolver.ResolvePath(String)
  fullName: VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  spec.csharp:
  - uid: VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
    name: ResolvePath
    nameWithType: IPathResolver.ResolvePath
    fullName: VDS.RDF.Configuration.IPathResolver.ResolvePath
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
    name: ResolvePath
    nameWithType: IPathResolver.ResolvePath
    fullName: VDS.RDF.Configuration.IPathResolver.ResolvePath
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
