### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.Permissions.IPermission
  commentId: T:VDS.RDF.Configuration.Permissions.IPermission
  id: IPermission
  parent: VDS.RDF.Configuration.Permissions
  children:
  - VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor(System.String)
  langs:
  - csharp
  - vb
  name: IPermission
  nameWithType: IPermission
  fullName: VDS.RDF.Configuration.Permissions.IPermission
  type: Interface
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: IPermission
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 58
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nInterface for Permission.\n"
  example: []
  syntax:
    content: public interface IPermission
    content.vb: Public Interface IPermission
  extensionMethods:
  - VDS.RDF.Configuration.Permissions.IPermission.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor(System.String)
  commentId: M:VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor(System.String)
  id: IsPermissionFor(System.String)
  parent: VDS.RDF.Configuration.Permissions.IPermission
  langs:
  - csharp
  - vb
  name: IsPermissionFor(String)
  nameWithType: IPermission.IsPermissionFor(String)
  fullName: VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor(System.String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: IsPermissionFor
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/Permissions/Permission.cs
    startLine: 65
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration.Permissions
  summary: "\nGets whether the Permission is for a specific action.\n"
  example: []
  syntax:
    content: bool IsPermissionFor(string action)
    parameters:
    - id: action
      type: System.String
      description: Action.
    return:
      type: System.Boolean
      description: ''
    content.vb: Function IsPermissionFor(action As String) As Boolean
  overload: VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor*
references:
- uid: VDS.RDF.Configuration.Permissions
  commentId: N:VDS.RDF.Configuration.Permissions
  name: VDS.RDF.Configuration.Permissions
  nameWithType: VDS.RDF.Configuration.Permissions
  fullName: VDS.RDF.Configuration.Permissions
- uid: VDS.RDF.Configuration.Permissions.IPermission.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<IPermission>()
  nameWithType: Extensions.AsEnumerable<IPermission>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.Permissions.IPermission>()
  nameWithType.vb: Extensions.AsEnumerable(Of IPermission)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.Permissions.IPermission)()
  name.vb: AsEnumerable(Of IPermission)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<IPermission>
    nameWithType: Extensions.AsEnumerable<IPermission>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.Permissions.IPermission>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of IPermission)
    nameWithType: Extensions.AsEnumerable(Of IPermission)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.Permissions.IPermission)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor*
  commentId: Overload:VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor
  name: IsPermissionFor
  nameWithType: IPermission.IsPermissionFor
  fullName: VDS.RDF.Configuration.Permissions.IPermission.IsPermissionFor
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
