### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.Resource
  commentId: N:VDS.RDF.Web.Configuration.Resource
  id: VDS.RDF.Web.Configuration.Resource
  children:
  - VDS.RDF.Web.Configuration.Resource.BaseDatasetHandlerConfiguration
  - VDS.RDF.Web.Configuration.Resource.BaseGraphHandlerConfiguration
  - VDS.RDF.Web.Configuration.Resource.DatasetHandlerConfiguration
  - VDS.RDF.Web.Configuration.Resource.GraphHandlerConfiguration
  langs:
  - csharp
  - vb
  name: VDS.RDF.Web.Configuration.Resource
  nameWithType: VDS.RDF.Web.Configuration.Resource
  fullName: VDS.RDF.Web.Configuration.Resource
  type: Namespace
  assemblies:
  - dotNetRDF.Web
references:
- uid: VDS.RDF.Web.Configuration.Resource.BaseDatasetHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Resource.BaseDatasetHandlerConfiguration
  parent: VDS.RDF.Web.Configuration.Resource
  name: BaseDatasetHandlerConfiguration
  nameWithType: BaseDatasetHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Resource.BaseDatasetHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Resource.DatasetHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Resource.DatasetHandlerConfiguration
  name: DatasetHandlerConfiguration
  nameWithType: DatasetHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Resource.DatasetHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Resource.BaseGraphHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Resource.BaseGraphHandlerConfiguration
  parent: VDS.RDF.Web.Configuration.Resource
  name: BaseGraphHandlerConfiguration
  nameWithType: BaseGraphHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Resource.BaseGraphHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Resource.GraphHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Resource.GraphHandlerConfiguration
  name: GraphHandlerConfiguration
  nameWithType: GraphHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Resource.GraphHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Resource
  commentId: N:VDS.RDF.Web.Configuration.Resource
  name: VDS.RDF.Web.Configuration.Resource
  nameWithType: VDS.RDF.Web.Configuration.Resource
  fullName: VDS.RDF.Web.Configuration.Resource
shouldSkipMarkup: true
