### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader
  commentId: T:VDS.RDF.Web.Configuration.WebConfigurationLoader
  id: WebConfigurationLoader
  parent: VDS.RDF.Web.Configuration
  children:
  - VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject(VDS.RDF.IGraph,Uri,String@)
  - VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph(HttpContext,String)
  - VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheDuration
  - VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheKey
  langs:
  - csharp
  - vb
  name: WebConfigurationLoader
  nameWithType: WebConfigurationLoader
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader
  type: Class
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: WebConfigurationLoader
    path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 37
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nStatic Helper class for Configuration loading for use in ASP.Net applicatons\n"
  example: []
  syntax:
    content: 'public static class WebConfigurationLoader : object'
    content.vb: >-
      Public Module WebConfigurationLoader
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheKey
  commentId: F:VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheKey
  id: WebConfigGraphCacheKey
  parent: VDS.RDF.Web.Configuration.WebConfigurationLoader
  langs:
  - csharp
  - vb
  name: WebConfigGraphCacheKey
  nameWithType: WebConfigurationLoader.WebConfigGraphCacheKey
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheKey
  type: Field
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: WebConfigGraphCacheKey
    path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 42
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nBase Cache Key for Configuration Graph caching\n"
  example: []
  syntax:
    content: public const String WebConfigGraphCacheKey = null
    return:
      type: String
    content.vb: Public Const WebConfigGraphCacheKey As String = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheDuration
  commentId: F:VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheDuration
  id: WebConfigGraphCacheDuration
  parent: VDS.RDF.Web.Configuration.WebConfigurationLoader
  langs:
  - csharp
  - vb
  name: WebConfigGraphCacheDuration
  nameWithType: WebConfigurationLoader.WebConfigGraphCacheDuration
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader.WebConfigGraphCacheDuration
  type: Field
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: WebConfigGraphCacheDuration
    path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 46
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nCache Duration for Configuration Graph caching\n"
  example: []
  syntax:
    content: public const int WebConfigGraphCacheDuration = null
    return:
      type: System.Int32
    content.vb: Public Const WebConfigGraphCacheDuration As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph(HttpContext,String)
  commentId: M:VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph(HttpContext,String)
  id: LoadConfigurationGraph(HttpContext,String)
  parent: VDS.RDF.Web.Configuration.WebConfigurationLoader
  langs:
  - csharp
  - vb
  name: LoadConfigurationGraph(HttpContext, String)
  nameWithType: WebConfigurationLoader.LoadConfigurationGraph(HttpContext, String)
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph(HttpContext, String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: LoadConfigurationGraph
    path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 54
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nGets the Configuration Graph with the given Filename returns it\n"
  example: []
  syntax:
    content: public static IGraph LoadConfigurationGraph(HttpContext context, String configFile)
    parameters:
    - id: context
      type: HttpContext
      description: HTTP Context
    - id: configFile
      type: String
      description: Configuration File
    return:
      type: VDS.RDF.IGraph
      description: ''
    content.vb: Public Shared Function LoadConfigurationGraph(context As HttpContext, configFile As String) As IGraph
  overload: VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject(VDS.RDF.IGraph,Uri,String@)
  commentId: M:VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject(VDS.RDF.IGraph,Uri,String@)
  id: FindObject(VDS.RDF.IGraph,Uri,String@)
  parent: VDS.RDF.Web.Configuration.WebConfigurationLoader
  langs:
  - csharp
  - vb
  name: FindObject(IGraph, Uri, out String)
  nameWithType: WebConfigurationLoader.FindObject(IGraph, Uri, out String)
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject(VDS.RDF.IGraph, Uri, out String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
      branch: maintenance/2.x
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: FindObject
    path: Libraries/dotNetRDF.Web/Configuration/WebConfigurationLoader.cs
    startLine: 93
  assemblies:
  - dotNetRDF.Web
  namespace: VDS.RDF.Web.Configuration
  summary: "\nFinds whether there is any Handler Configuration for a wildcard path that the current request path matches\n"
  example: []
  syntax:
    content: public static INode FindObject(IGraph g, Uri requestUri, out String matchedPath)
    parameters:
    - id: g
      type: VDS.RDF.IGraph
      description: Configuration Graph
    - id: requestUri
      type: Uri
      description: Request URI
    - id: matchedPath
      type: String
      description: The resulting matched path
    return:
      type: VDS.RDF.INode
      description: ''
    content.vb: Public Shared Function FindObject(g As IGraph, requestUri As Uri, ByRef matchedPath As String) As INode
  overload: VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject*
  nameWithType.vb: WebConfigurationLoader.FindObject(IGraph, Uri, ByRef String)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject(VDS.RDF.IGraph, Uri, ByRef String)
  name.vb: FindObject(IGraph, Uri, ByRef String)
references:
- uid: VDS.RDF.Web.Configuration
  commentId: N:VDS.RDF.Web.Configuration
  name: VDS.RDF.Web.Configuration
  nameWithType: VDS.RDF.Web.Configuration
  fullName: VDS.RDF.Web.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: String
  isExternal: true
  name: String
  nameWithType: String
  fullName: String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph*
  commentId: Overload:VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph
  name: LoadConfigurationGraph
  nameWithType: WebConfigurationLoader.LoadConfigurationGraph
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader.LoadConfigurationGraph
- uid: HttpContext
  isExternal: true
  name: HttpContext
  nameWithType: HttpContext
  fullName: HttpContext
- uid: VDS.RDF.IGraph
  commentId: T:VDS.RDF.IGraph
  parent: VDS.RDF
  name: IGraph
  nameWithType: IGraph
  fullName: VDS.RDF.IGraph
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject*
  commentId: Overload:VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject
  name: FindObject
  nameWithType: WebConfigurationLoader.FindObject
  fullName: VDS.RDF.Web.Configuration.WebConfigurationLoader.FindObject
- uid: Uri
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: Uri
- uid: VDS.RDF.INode
  commentId: T:VDS.RDF.INode
  parent: VDS.RDF
  name: INode
  nameWithType: INode
  fullName: VDS.RDF.INode
shouldSkipMarkup: true
