### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.Protocol
  commentId: N:VDS.RDF.Web.Configuration.Protocol
  id: VDS.RDF.Web.Configuration.Protocol
  children:
  - VDS.RDF.Web.Configuration.Protocol.BaseProtocolHandlerConfiguration
  - VDS.RDF.Web.Configuration.Protocol.ProtocolHandlerConfiguration
  langs:
  - csharp
  - vb
  name: VDS.RDF.Web.Configuration.Protocol
  nameWithType: VDS.RDF.Web.Configuration.Protocol
  fullName: VDS.RDF.Web.Configuration.Protocol
  type: Namespace
  assemblies:
  - dotNetRDF.Web
references:
- uid: VDS.RDF.Web.Configuration.Protocol.BaseProtocolHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Protocol.BaseProtocolHandlerConfiguration
  parent: VDS.RDF.Web.Configuration.Protocol
  name: BaseProtocolHandlerConfiguration
  nameWithType: BaseProtocolHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Protocol.BaseProtocolHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Protocol.ProtocolHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Protocol.ProtocolHandlerConfiguration
  name: ProtocolHandlerConfiguration
  nameWithType: ProtocolHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Protocol.ProtocolHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Protocol
  commentId: N:VDS.RDF.Web.Configuration.Protocol
  name: VDS.RDF.Web.Configuration.Protocol
  nameWithType: VDS.RDF.Web.Configuration.Protocol
  fullName: VDS.RDF.Web.Configuration.Protocol
