### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.ISettingsProvider
  commentId: T:VDS.RDF.Configuration.ISettingsProvider
  id: ISettingsProvider
  parent: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.ISettingsProvider.GetSetting(System.String)
  langs:
  - csharp
  - vb
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: VDS.RDF.Configuration.ISettingsProvider
  type: Interface
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ISettingsProvider.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: ISettingsProvider
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ISettingsProvider.cs
    startLine: 31
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nGives access to application settings from external source.\n"
  example: []
  syntax:
    content: public interface ISettingsProvider
    content.vb: Public Interface ISettingsProvider
  extensionMethods:
  - VDS.RDF.Configuration.ISettingsProvider.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VDS.RDF.Configuration.ISettingsProvider.GetSetting(System.String)
  commentId: M:VDS.RDF.Configuration.ISettingsProvider.GetSetting(System.String)
  id: GetSetting(System.String)
  parent: VDS.RDF.Configuration.ISettingsProvider
  langs:
  - csharp
  - vb
  name: GetSetting(String)
  nameWithType: ISettingsProvider.GetSetting(String)
  fullName: VDS.RDF.Configuration.ISettingsProvider.GetSetting(System.String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ISettingsProvider.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: GetSetting
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ISettingsProvider.cs
    startLine: 37
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nGets a setting for the provided key.\n"
  example: []
  syntax:
    content: string GetSetting(string key)
    parameters:
    - id: key
      type: System.String
    return:
      type: System.String
      description: null if the <code data-dev-comment-type="paramref" class="paramref">key</code> was not found.
    content.vb: Function GetSetting(key As String) As String
  overload: VDS.RDF.Configuration.ISettingsProvider.GetSetting*
references:
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: VDS.RDF.Configuration.ISettingsProvider.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<ISettingsProvider>()
  nameWithType: Extensions.AsEnumerable<ISettingsProvider>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.ISettingsProvider>()
  nameWithType.vb: Extensions.AsEnumerable(Of ISettingsProvider)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.ISettingsProvider)()
  name.vb: AsEnumerable(Of ISettingsProvider)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<ISettingsProvider>
    nameWithType: Extensions.AsEnumerable<ISettingsProvider>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.ISettingsProvider>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of ISettingsProvider)
    nameWithType: Extensions.AsEnumerable(Of ISettingsProvider)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.ISettingsProvider)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.ISettingsProvider.GetSetting*
  commentId: Overload:VDS.RDF.Configuration.ISettingsProvider.GetSetting
  name: GetSetting
  nameWithType: ISettingsProvider.GetSetting
  fullName: VDS.RDF.Configuration.ISettingsProvider.GetSetting
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
