### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Web.Configuration.Query
  commentId: N:VDS.RDF.Web.Configuration.Query
  id: VDS.RDF.Web.Configuration.Query
  children:
  - VDS.RDF.Web.Configuration.Query.BaseQueryHandlerConfiguration
  - VDS.RDF.Web.Configuration.Query.QueryHandlerConfiguration
  langs:
  - csharp
  - vb
  name: VDS.RDF.Web.Configuration.Query
  nameWithType: VDS.RDF.Web.Configuration.Query
  fullName: VDS.RDF.Web.Configuration.Query
  type: Namespace
  assemblies:
  - dotNetRDF.Web
references:
- uid: VDS.RDF.Web.Configuration.Query.BaseQueryHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Query.BaseQueryHandlerConfiguration
  parent: VDS.RDF.Web.Configuration.Query
  name: BaseQueryHandlerConfiguration
  nameWithType: BaseQueryHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Query.BaseQueryHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Query.QueryHandlerConfiguration
  commentId: T:VDS.RDF.Web.Configuration.Query.QueryHandlerConfiguration
  name: QueryHandlerConfiguration
  nameWithType: QueryHandlerConfiguration
  fullName: VDS.RDF.Web.Configuration.Query.QueryHandlerConfiguration
- uid: VDS.RDF.Web.Configuration.Query
  commentId: N:VDS.RDF.Web.Configuration.Query
  name: VDS.RDF.Web.Configuration.Query
  nameWithType: VDS.RDF.Web.Configuration.Query
  fullName: VDS.RDF.Web.Configuration.Query
shouldSkipMarkup: true
