### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.IPathResolver
  commentId: T:VDS.RDF.Configuration.IPathResolver
  id: IPathResolver
  parent: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  langs:
  - csharp
  - vb
  name: IPathResolver
  nameWithType: IPathResolver
  fullName: VDS.RDF.Configuration.IPathResolver
  type: Interface
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: IPathResolver
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 73
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nInteface for Objects which can resolve paths specified for Configuration properties.\n"
  example: []
  syntax:
    content: public interface IPathResolver
    content.vb: Public Interface IPathResolver
  extensionMethods:
  - VDS.RDF.Configuration.IPathResolver.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  commentId: M:VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  id: ResolvePath(System.String)
  parent: VDS.RDF.Configuration.IPathResolver
  langs:
  - csharp
  - vb
  name: ResolvePath(String)
  nameWithType: IPathResolver.ResolvePath(String)
  fullName: VDS.RDF.Configuration.IPathResolver.ResolvePath(System.String)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: ResolvePath
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 80
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nResolves a Path.\n"
  example: []
  syntax:
    content: string ResolvePath(string path)
    parameters:
    - id: path
      type: System.String
      description: Path.
    return:
      type: System.String
      description: ''
    content.vb: Function ResolvePath(path As String) As String
  overload: VDS.RDF.Configuration.IPathResolver.ResolvePath*
references:
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: VDS.RDF.Configuration.IPathResolver.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<IPathResolver>()
  nameWithType: Extensions.AsEnumerable<IPathResolver>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IPathResolver>()
  nameWithType.vb: Extensions.AsEnumerable(Of IPathResolver)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IPathResolver)()
  name.vb: AsEnumerable(Of IPathResolver)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<IPathResolver>
    nameWithType: Extensions.AsEnumerable<IPathResolver>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IPathResolver>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of IPathResolver)
    nameWithType: Extensions.AsEnumerable(Of IPathResolver)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IPathResolver)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.IPathResolver.ResolvePath*
  commentId: Overload:VDS.RDF.Configuration.IPathResolver.ResolvePath
  name: ResolvePath
  nameWithType: IPathResolver.ResolvePath
  fullName: VDS.RDF.Configuration.IPathResolver.ResolvePath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
