### YamlMime:ManagedReference
items:
- uid: VDS.RDF.Configuration.IObjectFactory
  commentId: T:VDS.RDF.Configuration.IObjectFactory
  id: IObjectFactory
  parent: VDS.RDF.Configuration
  children:
  - VDS.RDF.Configuration.IObjectFactory.CanLoadObject(System.Type)
  - VDS.RDF.Configuration.IObjectFactory.TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,System.Type,System.Object@)
  langs:
  - csharp
  - vb
  name: IObjectFactory
  nameWithType: IObjectFactory
  fullName: VDS.RDF.Configuration.IObjectFactory
  type: Interface
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: IObjectFactory
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 33
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nInterface for Object Factories which are factory classes that can create Objects based on configuration information in a Graph.\n"
  example: []
  syntax:
    content: public interface IObjectFactory
    content.vb: Public Interface IObjectFactory
  extensionMethods:
  - VDS.RDF.Configuration.IObjectFactory.VDS.RDF.Extensions.AsEnumerable``1
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VDS.RDF.Configuration.IObjectFactory.TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,System.Type,System.Object@)
  commentId: M:VDS.RDF.Configuration.IObjectFactory.TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,System.Type,System.Object@)
  id: TryLoadObject(VDS.RDF.IGraph,VDS.RDF.INode,System.Type,System.Object@)
  parent: VDS.RDF.Configuration.IObjectFactory
  langs:
  - csharp
  - vb
  name: TryLoadObject(IGraph, INode, Type, out Object)
  nameWithType: IObjectFactory.TryLoadObject(IGraph, INode, Type, out Object)
  fullName: VDS.RDF.Configuration.IObjectFactory.TryLoadObject(VDS.RDF.IGraph, VDS.RDF.INode, System.Type, out System.Object)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: TryLoadObject
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 48
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nAttempts to load an Object of the given type identified by the given Node and returned as the Type that this loader generates.\n"
  remarks: "\n<p>\nThe Factory should not throw an error if some required configuration is missing as another factory further down the processing chain may still be able to create the object.  If the factory encounters errors and all the required configuration information is present then that error should be thrown i.e. class instantiation throws an error or a call to load an object that this object requires fails.\n</p>\n"
  example: []
  syntax:
    content: bool TryLoadObject(IGraph g, INode objNode, Type targetType, out object obj)
    parameters:
    - id: g
      type: VDS.RDF.IGraph
      description: Configuration Graph.
    - id: objNode
      type: VDS.RDF.INode
      description: Object Node.
    - id: targetType
      type: System.Type
      description: Target Type.
    - id: obj
      type: System.Object
      description: Created Object.
    return:
      type: System.Boolean
      description: True if the loader succeeded in creating an Object.
    content.vb: Function TryLoadObject(g As IGraph, objNode As INode, targetType As Type, ByRef obj As Object) As Boolean
  overload: VDS.RDF.Configuration.IObjectFactory.TryLoadObject*
  nameWithType.vb: IObjectFactory.TryLoadObject(IGraph, INode, Type, ByRef Object)
  fullName.vb: VDS.RDF.Configuration.IObjectFactory.TryLoadObject(VDS.RDF.IGraph, VDS.RDF.INode, System.Type, ByRef System.Object)
  name.vb: TryLoadObject(IGraph, INode, Type, ByRef Object)
- uid: VDS.RDF.Configuration.IObjectFactory.CanLoadObject(System.Type)
  commentId: M:VDS.RDF.Configuration.IObjectFactory.CanLoadObject(System.Type)
  id: CanLoadObject(System.Type)
  parent: VDS.RDF.Configuration.IObjectFactory
  langs:
  - csharp
  - vb
  name: CanLoadObject(Type)
  nameWithType: IObjectFactory.CanLoadObject(Type)
  fullName: VDS.RDF.Configuration.IObjectFactory.CanLoadObject(System.Type)
  type: Method
  source:
    remote:
      path: Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
      branch: master
      repo: https://github.com/dotnetrdf/dotnetrdf.git
    id: CanLoadObject
    path: ../../dotNetRDF/Libraries/dotNetRDF/Configuration/ConfigurationInterfaces.cs
    startLine: 55
  assemblies:
  - dotNetRDF
  namespace: VDS.RDF.Configuration
  summary: "\nReturns whether this Factory is capable of creating objects of the given type.\n"
  example: []
  syntax:
    content: bool CanLoadObject(Type t)
    parameters:
    - id: t
      type: System.Type
      description: Target Type.
    return:
      type: System.Boolean
      description: ''
    content.vb: Function CanLoadObject(t As Type) As Boolean
  overload: VDS.RDF.Configuration.IObjectFactory.CanLoadObject*
references:
- uid: VDS.RDF.Configuration
  commentId: N:VDS.RDF.Configuration
  name: VDS.RDF.Configuration
  nameWithType: VDS.RDF.Configuration
  fullName: VDS.RDF.Configuration
- uid: VDS.RDF.Configuration.IObjectFactory.VDS.RDF.Extensions.AsEnumerable``1
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  parent: VDS.RDF.Extensions
  definition: VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<IObjectFactory>()
  nameWithType: Extensions.AsEnumerable<IObjectFactory>()
  fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IObjectFactory>()
  nameWithType.vb: Extensions.AsEnumerable(Of IObjectFactory)()
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IObjectFactory)()
  name.vb: AsEnumerable(Of IObjectFactory)()
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable<IObjectFactory>
    nameWithType: Extensions.AsEnumerable<IObjectFactory>
    fullName: VDS.RDF.Extensions.AsEnumerable<VDS.RDF.Configuration.IObjectFactory>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1
    name: AsEnumerable(Of IObjectFactory)
    nameWithType: Extensions.AsEnumerable(Of IObjectFactory)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of VDS.RDF.Configuration.IObjectFactory)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
  commentId: M:VDS.RDF.Extensions.AsEnumerable``1(``0)
  name: AsEnumerable<T>(T)
  nameWithType: Extensions.AsEnumerable<T>(T)
  fullName: VDS.RDF.Extensions.AsEnumerable<T>(T)
  nameWithType.vb: Extensions.AsEnumerable(Of T)(T)
  fullName.vb: VDS.RDF.Extensions.AsEnumerable(Of T)(T)
  name.vb: AsEnumerable(Of T)(T)
  spec.csharp:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable<T>
    nameWithType: Extensions.AsEnumerable<T>
    fullName: VDS.RDF.Extensions.AsEnumerable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VDS.RDF.Extensions.AsEnumerable``1(``0)
    name: AsEnumerable(Of T)
    nameWithType: Extensions.AsEnumerable(Of T)
    fullName: VDS.RDF.Extensions.AsEnumerable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VDS.RDF.Extensions
  commentId: T:VDS.RDF.Extensions
  parent: VDS.RDF
  name: Extensions
  nameWithType: Extensions
  fullName: VDS.RDF.Extensions
- uid: VDS.RDF
  commentId: N:VDS.RDF
  name: VDS.RDF
  nameWithType: VDS.RDF
  fullName: VDS.RDF
- uid: VDS.RDF.Configuration.IObjectFactory.TryLoadObject*
  commentId: Overload:VDS.RDF.Configuration.IObjectFactory.TryLoadObject
  name: TryLoadObject
  nameWithType: IObjectFactory.TryLoadObject
  fullName: VDS.RDF.Configuration.IObjectFactory.TryLoadObject
- uid: VDS.RDF.IGraph
  commentId: T:VDS.RDF.IGraph
  parent: VDS.RDF
  name: IGraph
  nameWithType: IGraph
  fullName: VDS.RDF.IGraph
- uid: VDS.RDF.INode
  commentId: T:VDS.RDF.INode
  parent: VDS.RDF
  name: INode
  nameWithType: INode
  fullName: VDS.RDF.INode
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VDS.RDF.Configuration.IObjectFactory.CanLoadObject*
  commentId: Overload:VDS.RDF.Configuration.IObjectFactory.CanLoadObject
  name: CanLoadObject
  nameWithType: IObjectFactory.CanLoadObject
  fullName: VDS.RDF.Configuration.IObjectFactory.CanLoadObject
